sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'stable'
  - v5

# make electron work
# source: https://github.com/juliangruber/electron-stream#travis (last checked on 2016-01-26)
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
